/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels.shortcut;

import com.vollyball.bean.Settings;
import com.vollyball.dao.SettingDao;
import com.vollyball.enums.Skill;
import com.vollyball.enums.SkillDescCriteriaPoint;
import com.vollyball.enums.SkillsDescCriteria;
import java.util.List;

/**
 *
 * @author nishant.vibhute
 */
public class PanShorcutView extends javax.swing.JPanel {

    SettingDao settingDao = new SettingDao();

    /**
     * Creates new form PanShorcutView
     */
    public PanShorcutView() {
        initComponents();
    }

    public void createTable() {

//        String html = "<html><table >";
//        String skillsRow = "";
//        for (Skill sk : Skill.values()) {
//
//            List<SkillsDescCriteria> lstskillsDescCriteria = SkillsDescCriteria.getViewableSkillDescCriteriaBySkill(sk.getId());
//            String skillsDescCriteriaRow = "";
//            int rowspanskillsDescCriteria = 0;
//            for (SkillsDescCriteria skillsDescCriteria : lstskillsDescCriteria) {
//                List<SkillDescCriteriaPoint> lstskillDescCriteriaPoint = SkillDescCriteriaPoint.getTypeBySkillDescId(skillsDescCriteria.getId());
//                String skillDescCriteriaPointRow = "";
//                for (SkillDescCriteriaPoint skillDescCriteriaPoint : lstskillDescCriteriaPoint) {
//
//                    Settings s = settingDao.getCodeForId(skillDescCriteriaPoint.getShortcutId());
//                    skillDescCriteriaPointRow = skillDescCriteriaPointRow + "<tr ><td >" + skillDescCriteriaPoint.getAbbreviation() + "</td><td>" + s.getCode() + "</td></tr>";
//
//                }
//
//                int rowspan = lstskillDescCriteriaPoint.size();
//                rowspanskillsDescCriteria = rowspanskillsDescCriteria + rowspan + 1;
//
//                skillsDescCriteriaRow = skillsDescCriteriaRow + "<tr ><td  rowspan='" + (rowspan + 1) + "'>" + skillsDescCriteria.getType() + "</td></tr> " + skillDescCriteriaPointRow;
//            }
//
//            skillsRow = skillsRow + "<tr ><td  rowspan='" + (rowspanskillsDescCriteria + 1) + "'>" + sk.getType() + "</td></tr>" + skillsDescCriteriaRow;
//
//        }
//        html = html + skillsRow + "</table></html>";
        String html = "<html><table >";
        String skillsRow = "";
        for (Skill sk : Skill.values()) {

            List<SkillsDescCriteria> lstskillsDescCriteria = SkillsDescCriteria.getViewableSkillDescCriteriaBySkill(sk.getId());
            String skillsDescCriteriaRow = "";
            int rowspanskillsDescCriteria = 0;
            for (SkillsDescCriteria skillsDescCriteria : lstskillsDescCriteria) {
                List<SkillDescCriteriaPoint> lstskillDescCriteriaPoint = SkillDescCriteriaPoint.getTypeBySkillDescId(skillsDescCriteria.getId());
                String skillDescCriteriaPointRow = "";
                for (SkillDescCriteriaPoint skillDescCriteriaPoint : lstskillDescCriteriaPoint) {

                    Settings s = settingDao.getCodeForId(skillDescCriteriaPoint.getShortcutId());
                    skillDescCriteriaPointRow = skillDescCriteriaPointRow + "<tr ><td >" + skillDescCriteriaPoint.getAbbreviation() + "</td><td>" + s.getCode() + "</td></tr>";

                }

                int rowspan = lstskillDescCriteriaPoint.size();
                rowspanskillsDescCriteria = rowspanskillsDescCriteria + rowspan + 2;

                skillsDescCriteriaRow = skillsDescCriteriaRow + "<tr ><td  rowspan='" + (rowspan + 1) + "'>" + skillsDescCriteria.getType() + "</td></tr> " + skillDescCriteriaPointRow + "<tr><td colspan=3><hr></td></tr>";
            }

            skillsRow = skillsRow + "<tr ><td  rowspan='" + (rowspanskillsDescCriteria + 1) + "'>" + sk.getType() + "</td></tr>" + skillsDescCriteriaRow;

        }
        html = html + skillsRow + "</table></html>";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTable = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(666, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTable.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 427, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTable;
    // End of variables declaration//GEN-END:variables
}
