/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.training.panel;

import com.vollyball.bean.Player;
import com.vollyball.controller.Controller;
import com.vollyball.training.bean.Batch;
import com.vollyball.training.bean.Trainee;
import com.vollyball.training.dao.BatchDao;
import java.awt.Color;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author #dabbu
 */
public class PanNewTrainee extends javax.swing.JPanel {

    BatchDao batchDao = new BatchDao();
    LinkedHashMap<String, Integer> batchMap;
    int batchId;
    int traineeId;
    Trainee trainee;
    int type;

    /**
     * Creates new form PanNewTrainee
     */
    public PanNewTrainee() {
        initComponents();
        List<Batch> batchList = batchDao.getBatchList();
        batchMap = new LinkedHashMap<>();
        team1combo1.addItem("Select");
        for (Batch batch : batchList) {
            batchMap.put(batch.getName(), batch.getId());
            team1combo1.addItem(batch.getName());
        }
        type = 1;

    }

    public PanNewTrainee(int batchId) {
        initComponents();
        this.batchId = batchId;
        List<Batch> batchList = batchDao.getBatchList();
        batchMap = new LinkedHashMap<>();
        for (Batch batch : batchList) {
            if (batchId == batch.getId()) {
                batchMap.put(batch.getName(), batch.getId());
                team1combo1.addItem(batch.getName());
            }
        }
        type = 2;
    }

    public PanNewTrainee(Trainee trainee) {
        initComponents();
        this.trainee = trainee;
        batchId = trainee.getBatchId();
        traineeId = trainee.getId();
        List<Batch> batchList = batchDao.getBatchList();
        List<Trainee> traineeList = batchDao.getTraineeList(trainee.getBatchId());
        batchMap = new LinkedHashMap<>();
        for (Batch batch : batchList) {
            if (trainee.getBatchId() == batch.getId()) {
                batchMap.put(batch.getName(), batch.getId());
                team1combo1.addItem(batch.getName());
            }
        }
        String traineeName = "";
        for (Trainee t : traineeList) {
            if (t.getId() == trainee.getId()) {
                traineeName = trainee.getName();
            }
        }
        txtTraineeName.setText(traineeName);
        type = 3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        team1combo1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        savePlayerLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTraineeName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        team1combo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Batch");

        jPanel8.setBackground(new java.awt.Color(57, 74, 108));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        savePlayerLabel.setBackground(new java.awt.Color(0, 153, 255));
        savePlayerLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        savePlayerLabel.setForeground(new java.awt.Color(255, 255, 255));
        savePlayerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        savePlayerLabel.setText("SAVE");
        savePlayerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savePlayerLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(savePlayerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(savePlayerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(57, 74, 108));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("New Trainee");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        txtTraineeName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTraineeName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Name");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(151, 288, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(team1combo1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTraineeName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(269, 269, 269)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(team1combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTraineeName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void savePlayerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savePlayerLabelMouseClicked
        // TODO add your handling code here:
        switch (type) {
            case 1:
                String msg = validateFields();
                if (!msg.isEmpty()) {
                    JOptionPane.showMessageDialog(this, msg);
                } else {
                    Trainee trainee = new Trainee();
                    trainee.setBatchId(team1combo1.getSelectedIndex());
                    trainee.setName(txtTraineeName.getText());

                    int id = batchDao.insertTrainee(trainee);

                    if (id != 0) {
                        Controller.createTraineeDailog.close();
                        JOptionPane.showMessageDialog(this, "Trainee '" + txtTraineeName.getText() + "' Added Successfully");
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to add Trainee");
                    }
                }
                break;
            case 2:
                String msg2 = validateFields();
                if (!msg2.isEmpty()) {
                    JOptionPane.showMessageDialog(this, msg2);
                } else {
                    Trainee trainee = new Trainee();
                    trainee.setBatchId(batchId);
                    trainee.setName(txtTraineeName.getText());

                    int id = batchDao.insertTrainee(trainee);

                    if (id != 0) {
                        Controller.panBatchTraineeList.setRow(batchId);
                        Controller.createTraineeDailog.close();
                        JOptionPane.showMessageDialog(this, "Trainee '" + txtTraineeName.getText() + "' Added Successfully");

                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to add Trainee");
                    }
                }
                break;
            case 3:
                String msg3 = validateFields();
                if (!msg3.isEmpty()) {
                    JOptionPane.showMessageDialog(this, msg3);
                } else {
                    Trainee trainee = new Trainee();
                    trainee.setId(traineeId);
                    trainee.setBatchId(batchId);
                    trainee.setName(txtTraineeName.getText());
                    int id = batchDao.updateTrainee(trainee);
                    if (id != 0) {
                        Controller.panBatchTraineeList.setRow(batchId);
                        Controller.createTraineeDailog.close();
                        JOptionPane.showMessageDialog(this, "Trainee '" + txtTraineeName.getText() + "' Updated Successfully");

                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to update Trainee");
                    }
                }
            default:
                Controller.panBatchTraineeList.setRow(batchId);
                break;
        }

    }//GEN-LAST:event_savePlayerLabelMouseClicked

    public String validateFields() {
        String msg = "";

        int k = 1;

        if (txtTraineeName.getText().equals("")) {
            msg = msg + "Name Cannot be Blank";
            txtTraineeName.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
        }

        if (team1combo1.getSelectedItem().equals("Select")) {
            msg = msg + "Select Batch";
            team1combo1.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.red));
        }

        return msg;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel savePlayerLabel;
    public javax.swing.JComboBox team1combo1;
    private javax.swing.JTextField txtTraineeName;
    // End of variables declaration//GEN-END:variables
}
