/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels.report;

import com.vollyball.bean.PlayerScores;
import com.vollyball.bean.TeamSkillScore;
import com.vollyball.dao.ReportDao;
import com.vollyball.dao.TeamReportDao;
import com.vollyball.enums.Skill;
import com.vollyball.renderer.TableHeaderRendererForReport;
import java.text.DecimalFormat;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author nishant.vibhute
 */
public class PanTeamReportSkillRow extends javax.swing.JPanel {

    TeamReportDao trd = new TeamReportDao();
    DecimalFormat df = new DecimalFormat("##.##%");
    ReportDao reportDao = new ReportDao();
    DefaultTableModel dm;

    /**
     * Creates new form PanTeamReportSkillRow
     */
    public PanTeamReportSkillRow(int cb, int skillId, int matchId, int team1id, int evaluationteamId) {
        initComponents();
        resizeColumns();
        skillName.setText(Skill.getNameById(skillId).getType());

        TeamSkillScore tsc = trd.getTeamSkillWiseScoreReport(cb, skillId, matchId, team1id, evaluationteamId);

        lblAttempt.setText("" + tsc.getTotalAttempt());

        double rate = tsc.getFive() == 0 || tsc.getTotalAttempt() == 0 ? 0 : (double) tsc.getFive() / (double) tsc.getTotalAttempt();
        lblSuccessRate.setText(rate == 0 ? "0%" : df.format(rate));

        rate = tsc.getOne() == 0 || tsc.getTotalAttempt() == 0 ? 0 : (double) tsc.getOne() / (double) tsc.getTotalAttempt();
        lblFailureRate.setText(rate == 0 ? "0%" : df.format(rate));

        dm = (DefaultTableModel) tblPlayerReport.getModel();

        List<PlayerScores> lsList = reportDao.getMatchReportForPlayerSkills(evaluationteamId, skillId);

        Collections.sort(lsList, new Comparator<PlayerScores>() {
            @Override
            public int compare(PlayerScores c1, PlayerScores c2) {

                return Double.compare(c2.getAttemptSuccessRate(), c1.getAttemptSuccessRate());
            }
        });

        for (int i = dm.getRowCount() - 1; i >= 0; i--) {
            dm.removeRow(i);
        }

        int j = 0;
        for (int i = 0; i < lsList.size(); i++) {

            if (i <= 6) {
                j++;
                PlayerScores p = lsList.get(i);
                Object[] row = {p.getPlayerName(), 
                    p.getTotalAttempt()==0?"-":p.getTotalAttempt(), 
                    p.getSuccessAttempt()==0?"-":p.getSuccessAttempt(), 
                    p.getAttemptSuccessRatePerc()=="0%"?"-":p.getAttemptSuccessRatePerc(), 
                    p.getFailureAttempt()==0?"-":p.getFailureAttempt(), 
                    p.getAttemptFailureRatePerc()=="0%"?"-":p.getAttemptFailureRatePerc()};
                dm.addRow(row);
            }

        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        JTableHeader header1 = tblPlayerReport.getTableHeader();
        header1.setDefaultRenderer(new TableHeaderRendererForReport(tblPlayerReport));
//        tblPlayerReport.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblPlayerReport.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblPlayerReport.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tblPlayerReport.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tblPlayerReport.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tblPlayerReport.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);

        for (int k = j; k < 6; k++) {
            Object[] row = {"", "", "", "", "", ""};
            dm.addRow(row);
        }

    }

    float[] columnWidthPercentage = {40.0f, 15.0f, 7.0f, 15.0f, 7.0f, 15.0f};

    private void resizeColumns() {
        int tW = tblPlayerReport.getPreferredSize().width;
        TableColumn column;
        TableColumnModel jTableColumnModel = tblPlayerReport.getColumnModel();
        int cantCols = jTableColumnModel.getColumnCount();
        for (int i = 0; i < cantCols; i++) {
            column = jTableColumnModel.getColumn(i);
            int pWidth = Math.round(columnWidthPercentage[i] * tW);
            column.setPreferredWidth(pWidth);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        skillName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAttempt = new javax.swing.JLabel();
        lblSuccessRate = new javax.swing.JLabel();
        lblFailureRate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlayerReport = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        skillName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        skillName.setText(" ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Total Attempt :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Success Rate   :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Failure Rate    :");
        jLabel4.setToolTipText("");

        lblAttempt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAttempt.setText("jLabel5");

        lblSuccessRate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblSuccessRate.setText("jLabel5");

        lblFailureRate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblFailureRate.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAttempt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSuccessRate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFailureRate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAttempt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSuccessRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblFailureRate))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.BorderLayout());

        tblPlayerReport.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblPlayerReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Player Name", "Att.", "+", "+ %", "-", "- %"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPlayerReport.setRowHeight(20);
        jScrollPane1.setViewportView(tblPlayerReport);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skillName)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(skillName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAttempt;
    private javax.swing.JLabel lblFailureRate;
    private javax.swing.JLabel lblSuccessRate;
    private javax.swing.JLabel skillName;
    private javax.swing.JTable tblPlayerReport;
    // End of variables declaration//GEN-END:variables
}
