/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels.report;

import com.vollyball.panels.*;
import com.vollyball.bean.ZoneHitCount;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;

/**
 *
 * @author nishant.vibhute
 */
public class PanZoneSkillwisePanel extends javax.swing.JPanel {

    ZoneHitCount zhc;

    /**
     * Creates new form PanZoneSkillwiseReport
     */
    public PanZoneSkillwisePanel() {
        initComponents();

        repaint();
    }

    public void setValues(ZoneHitCount zhc) {
        this.zhc = zhc;
        repaint();
    }

    public void paint(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;

        if (zhc.isIsMaxSuccess()) {
            Polygon poly = new Polygon(new int[]{0, 50, 50, 0}, new int[]{0, 0, 10, 40}, 4);
            g2.setColor(new Color(34, 177, 76));
            g2.fill(poly);
        }

        if (zhc.isIsMaxFail()) {
            Polygon poly2 = new Polygon(new int[]{0, 50, 50, 0}, new int[]{40, 10, 50, 50}, 4);
            g2.setColor(new Color(182, 14, 22));
            g2.fill(poly2);
        }
        g2.setStroke(new BasicStroke(1));
        g2.setColor(Color.BLACK);
        g2.drawLine(0, 40, 50, 10);

        FontMetrics fm = g.getFontMetrics();
        int centerX = 5, centerY = 15;
        double textWidth = fm.getStringBounds("1%", g).getWidth();
        Font font = new Font("Serif", Font.BOLD, 11);
        g2.setFont(font);
        g.setColor(Color.BLACK);
        g.drawString("S:" + zhc.getSuccessPerc() + "%", centerX, centerY);

        centerX = 20;
        centerY = 43;
//        textWidth = fm.getStringBounds("%" + zone, g).getWidth();
        g2.setFont(font);
        g.setColor(Color.BLACK);
        g.drawString("F:" + zhc.getFailPerc() + "%", centerX, centerY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
