/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels.report;

import com.vollyball.bean.Player;
import com.vollyball.bean.PlayerPositionBean;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author nishant.vibhute
 */
public class PanZoneRotationBlock extends javax.swing.JPanel {

    /**
     * Creates new form PanZoneRotationBlock
     */
    public PanZoneRotationBlock(PlayerPositionBean pb, int i) {
        initComponents();

        rotation1.setLayout(new GridLayout(2, 3));

        lblRotationNo.setText("Rotation " + i);
        lblStrongPerc.setText(pb.getSuccessPerc() + "%");
        lblFailurePerc1.setText(pb.getLossPerc() + "%");
        int[] positions = {4, 3, 2, 5, 6, 1};

        for (int pos : positions) {

            Player player = pb.pos.get(pos);
            lblCount.setText("" + pb.getRotationCount());
            JPanel pan = new JPanel(new BorderLayout());
            pan.setSize(40, 40);
            pan.setBorder(new LineBorder(Color.BLACK, 1));
            PanZoneRotationPanel p = new PanZoneRotationPanel(player);
            pan.add(p, BorderLayout.CENTER);
            rotation1.add(pan);
        }

//        for (int i = 0; i < 2; i++) {
//            for (int j = 0; j < 3; j++) {
//
//                JPanel pan = new JPanel(new BorderLayout());
//                pan.setSize(40, 40);
//                pan.setBorder(new LineBorder(Color.BLACK, 1));
//                PanZoneRotationPanel p = new PanZoneRotationPanel(i);
//                pan.add(p, BorderLayout.CENTER);
//                rotation1.add(pan);
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panRotation = new javax.swing.JPanel();
        rotation1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblRotationNo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblStrongPerc = new javax.swing.JLabel();
        lblFailurePerc1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        panRotation.setBackground(new java.awt.Color(255, 255, 255));
        panRotation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rotation1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout rotation1Layout = new javax.swing.GroupLayout(rotation1);
        rotation1.setLayout(rotation1Layout);
        rotation1Layout.setHorizontalGroup(
            rotation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );
        rotation1Layout.setVerticalGroup(
            rotation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblRotationNo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRotationNo.setText("Rotation 1");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Win : ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Loss : ");

        lblStrongPerc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblStrongPerc.setText("100%");

        lblFailurePerc1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblFailurePerc1.setText("100%");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("PRNR  : ");

        lblCount.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCount.setText("0");

        javax.swing.GroupLayout panRotationLayout = new javax.swing.GroupLayout(panRotation);
        panRotation.setLayout(panRotationLayout);
        panRotationLayout.setHorizontalGroup(
            panRotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRotationLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panRotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panRotationLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(lblStrongPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRotationNo)
                    .addGroup(panRotationLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panRotationLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFailurePerc1))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panRotationLayout.setVerticalGroup(
            panRotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRotationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRotationNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblStrongPerc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panRotationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblFailurePerc1))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRotationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panRotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblFailurePerc1;
    private javax.swing.JLabel lblRotationNo;
    private javax.swing.JLabel lblStrongPerc;
    private javax.swing.JPanel panRotation;
    private javax.swing.JPanel rotation1;
    // End of variables declaration//GEN-END:variables
}
