/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels;

import com.vollyball.bean.CompetitionBean;
import com.vollyball.bean.Team;
import com.vollyball.controller.Controller;
import com.vollyball.dao.TeamDao;
import com.vollyball.dialog.CreateMatchDialog;
import com.vollyball.dialog.CreateTeamDialog;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nishant.vibhute
 */
public class PanComptitionHome extends javax.swing.JPanel {

    public CreateMatchDialog matchDialog;
    public CreateTeamDialog teamDialog;

    /**
     * Creates new form PanComptitionHome
     */
    public PanComptitionHome(CompetitionBean cb) {

        initComponents();
        lblComHeading.setText(cb.getName());
        panNewButton.setVisible(false);
        Controller.competitionId = cb.getId();
        Controller.panTeams = new PanTeams();
        Controller.panMatches = new PanMatches();
        panMatches.setBackground(new Color(255, 255, 255));
        panTeams.setBackground(new Color(57, 74, 108));
        lblMatch.setForeground(new Color(57, 74, 108));
        lblTeam.setForeground(new Color(255, 255, 255));
        panNewButton.setVisible(true);
        lblNewButton.setText("New Match");
        Dimension dim = panCompetitionContent.getSize();
        Controller.panMatches.setBounds(0, 0, dim.width, dim.height);
        panCompetitionContent.add(Controller.panMatches);
        Controller.panTeams.setVisible(false);
        Controller.panMatches.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblComHeading = new javax.swing.JLabel();
        panNewButton = new javax.swing.JPanel();
        lblNewButton = new javax.swing.JLabel();
        panCompetitionContent = new javax.swing.JPanel();
        panMatches = new javax.swing.JPanel();
        lblMatch = new javax.swing.JLabel();
        panTeams = new javax.swing.JPanel();
        lblTeam = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(57, 74, 108));

        lblComHeading.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblComHeading.setForeground(new java.awt.Color(244, 195, 1));
        lblComHeading.setText("jLabel1");

        panNewButton.setBackground(new java.awt.Color(244, 195, 1));
        panNewButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNewButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNewButton.setForeground(new java.awt.Color(27, 34, 136));
        lblNewButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewButton.setText("New Match");
        lblNewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panNewButtonLayout = new javax.swing.GroupLayout(panNewButton);
        panNewButton.setLayout(panNewButtonLayout);
        panNewButtonLayout.setHorizontalGroup(
            panNewButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panNewButtonLayout.setVerticalGroup(
            panNewButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblComHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                .addComponent(panNewButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblComHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panNewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        panCompetitionContent.setBackground(new java.awt.Color(255, 255, 255));
        panCompetitionContent.setLayout(new java.awt.BorderLayout());

        panMatches.setBackground(new java.awt.Color(255, 255, 255));

        lblMatch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMatch.setForeground(new java.awt.Color(57, 74, 108));
        lblMatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMatch.setText("MATCHES");
        lblMatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMatchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panMatchesLayout = new javax.swing.GroupLayout(panMatches);
        panMatches.setLayout(panMatchesLayout);
        panMatchesLayout.setHorizontalGroup(
            panMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMatchesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblMatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panMatchesLayout.setVerticalGroup(
            panMatchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMatchesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panTeams.setBackground(new java.awt.Color(57, 74, 108));

        lblTeam.setBackground(new java.awt.Color(27, 34, 136));
        lblTeam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTeam.setForeground(new java.awt.Color(255, 255, 255));
        lblTeam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeam.setText("TEAMS");
        lblTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTeamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panTeamsLayout = new javax.swing.GroupLayout(panTeams);
        panTeams.setLayout(panTeamsLayout);
        panTeamsLayout.setHorizontalGroup(
            panTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panTeamsLayout.setVerticalGroup(
            panTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTeam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panCompetitionContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panMatches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panTeams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panTeams, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panMatches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(panCompetitionContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblMatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMatchMouseClicked
        // TODO add your handling code here:

        panMatches.setBackground(new Color(255, 255, 255));
        panTeams.setBackground(new Color(57, 74, 108));
        lblMatch.setForeground(new Color(57, 74, 108));
        lblTeam.setForeground(new Color(255, 255, 255));
        panNewButton.setVisible(true);
        lblNewButton.setText("New Match");
        Dimension dim = panCompetitionContent.getSize();
        Controller.panMatches.setBounds(0, 0, dim.width, dim.height);
        panCompetitionContent.add(Controller.panMatches);
        Controller.panTeams.setVisible(false);
        Controller.panMatches.setVisible(true);
    }//GEN-LAST:event_lblMatchMouseClicked

    private void lblTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTeamMouseClicked
        // TODO add your handling code here:
        Controller.panTeams.setVisible(true);
        Controller.panMatches.setVisible(false);
        TeamDao teamDao = new TeamDao();

        panMatches.setBackground(new Color(57, 74, 108));
        panTeams.setBackground(new Color(255, 255, 255));
        lblTeam.setForeground(new Color(57, 74, 108));
        lblMatch.setForeground(new Color(255, 255, 255));
        panNewButton.setVisible(true);
        lblNewButton.setText("New Team");
        Dimension dim = panCompetitionContent.getSize();
//        Controller.panTeams.setBounds(0, 0, dim.width, dim.height);
        panCompetitionContent.add(Controller.panTeams, BorderLayout.CENTER);
        DefaultTableModel model = (DefaultTableModel) Controller.panTeams.tbTeamList.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        List<Team> teams = teamDao.getTeams(Controller.competitionId);

        int i = 0;
        for (Team team : teams) {
            i++;
            Object[] row = {i, team.getName(), team};
            model.addRow(row);
        }
    }//GEN-LAST:event_lblTeamMouseClicked

    private void lblNewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewButtonMouseClicked
        // TODO add your handling code here:
        Object o = evt.getSource();
        String t = ((JLabel) o).getText();
        if (t.equals("New Match")) {
            matchDialog = new CreateMatchDialog();
            matchDialog.init();
            matchDialog.show();
        } else {
            teamDialog = new CreateTeamDialog();
            teamDialog.init();
            teamDialog.show();
        }
    }//GEN-LAST:event_lblNewButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblComHeading;
    private javax.swing.JLabel lblMatch;
    private javax.swing.JLabel lblNewButton;
    private javax.swing.JLabel lblTeam;
    private javax.swing.JPanel panCompetitionContent;
    private javax.swing.JPanel panMatches;
    private javax.swing.JPanel panNewButton;
    private javax.swing.JPanel panTeams;
    // End of variables declaration//GEN-END:variables
}
