/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author #dabbu
 */
public class PanEvaluationSubstitutes extends javax.swing.JPanel {

    int setNum;
    int matchEvaluationTeamId;

    /**
     * Creates new form PanEvaluationSubstitutes
     */
    public PanEvaluationSubstitutes(int setNum, int matchEvaluationTeamId) {
        initComponents();
        this.setNum = setNum;
        this.matchEvaluationTeamId = matchEvaluationTeamId;
        homeSubstitute();

    }

    public void homeSubstitute() {
        substituteHome.setBackground(new Color(57, 74, 108));
        substituteOpp.setBackground(new Color(255, 255, 255));
        lblhomeSub.setForeground(Color.WHITE);
        lblOppSub.setForeground(new Color(57, 74, 108));
        PanEvaluationSubstitute panEvaluationSubstitute = new PanEvaluationSubstitute(setNum, matchEvaluationTeamId);
        substitutePanel.removeAll();
        substitutePanel.add(panEvaluationSubstitute, BorderLayout.CENTER);
        substitutePanel.validate();
        substitutePanel.repaint();
        substitutePanel.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        substituteHome = new javax.swing.JPanel();
        lblhomeSub = new javax.swing.JTextField();
        substituteOpp = new javax.swing.JPanel();
        lblOppSub = new javax.swing.JTextField();
        substitutePanel = new javax.swing.JPanel();

        substituteHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        substituteHome.setForeground(new java.awt.Color(0, 0, 204));

        lblhomeSub.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblhomeSub.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblhomeSub.setText("Home Substitute");
        lblhomeSub.setBorder(null);
        lblhomeSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblhomeSub.setOpaque(false);
        lblhomeSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhomeSubMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout substituteHomeLayout = new javax.swing.GroupLayout(substituteHome);
        substituteHome.setLayout(substituteHomeLayout);
        substituteHomeLayout.setHorizontalGroup(
            substituteHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(substituteHomeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblhomeSub, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        substituteHomeLayout.setVerticalGroup(
            substituteHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblhomeSub, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        substituteOpp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblOppSub.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOppSub.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblOppSub.setText("Opponent Substitute");
        lblOppSub.setBorder(null);
        lblOppSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOppSub.setOpaque(false);
        lblOppSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOppSubMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout substituteOppLayout = new javax.swing.GroupLayout(substituteOpp);
        substituteOpp.setLayout(substituteOppLayout);
        substituteOppLayout.setHorizontalGroup(
            substituteOppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, substituteOppLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lblOppSub, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        substituteOppLayout.setVerticalGroup(
            substituteOppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(substituteOppLayout.createSequentialGroup()
                .addComponent(lblOppSub, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        substitutePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout substitutePanelLayout = new javax.swing.GroupLayout(substitutePanel);
        substitutePanel.setLayout(substitutePanelLayout);
        substitutePanelLayout.setHorizontalGroup(
            substitutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        substitutePanelLayout.setVerticalGroup(
            substitutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(substituteHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(substituteOpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(substitutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(substituteOpp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(substituteHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(substitutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblhomeSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeSubMouseClicked
        // TODO add your handling code here:
        homeSubstitute();
    }//GEN-LAST:event_lblhomeSubMouseClicked

    private void lblOppSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOppSubMouseClicked
        // TODO add your handling code here:
        substituteHome.setBackground(new Color(255, 255, 255));
        substituteOpp.setBackground(new Color(57, 74, 108));
        lblhomeSub.setForeground(new Color(57, 74, 108));
        lblOppSub.setForeground(Color.WHITE);
        PanEvaluationSubstituteOpponent panEvaluationOpponent = new PanEvaluationSubstituteOpponent(setNum, matchEvaluationTeamId);
        substitutePanel.removeAll();
        substitutePanel.add(panEvaluationOpponent, BorderLayout.CENTER);
        substitutePanel.validate();
        substitutePanel.repaint();
        substitutePanel.setVisible(true);
    }//GEN-LAST:event_lblOppSubMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField lblOppSub;
    private javax.swing.JTextField lblhomeSub;
    private javax.swing.JPanel substituteHome;
    private javax.swing.JPanel substituteOpp;
    private javax.swing.JPanel substitutePanel;
    // End of variables declaration//GEN-END:variables
}
