/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels;

import com.vollyball.bean.RallyEvaluationSkillScore;
import com.vollyball.controller.Controller;
import com.vollyball.enums.Skill;
import com.vollyball.enums.SkillDescCriteriaPoint;
import com.vollyball.enums.SkillsDescCriteria;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JTextField;

/**
 *
 * @author nishant.vibhute
 */
public class PanEvaluationRallyDetailsEdit extends javax.swing.JPanel {

    LinkedHashMap<Integer, PanSkillDescCriteriaEdit> skillDescIdPanMap = new LinkedHashMap<>();
    RallyEvaluationSkillScore rallyEvaluationSkillScore;
    PanEvaluationRowDetail p;
    String code;

    /**
     * Creates new form PanEvaluationRallyDetailsEdit
     */
    public PanEvaluationRallyDetailsEdit(String skill, String chestNo, String score, RallyEvaluationSkillScore rallyEvaluationSkillScore, PanEvaluationRowDetail p) {
        initComponents();
        this.rallyEvaluationSkillScore = rallyEvaluationSkillScore;
        this.p = p;
        lblSkill.setText(skill);
        txtChestNo.setText(chestNo);
        txtScore.setText("" + rallyEvaluationSkillScore.getScore());

        int skillId = Skill.getIdByName(skill).getId();
        List<SkillsDescCriteria> lst = SkillsDescCriteria.getSkillDescCriteriaBySkillandView(skillId);

        int rows = lst.size() / 2;
        int remainder = lst.size() % 2;

        if (remainder != 0) {
            rows = rows + 1;
        }

        panDesc1.setLayout(new GridLayout(rows, 1));
        panDesc2.setLayout(new GridLayout(rows, 1));
        int i = 0;
        for (SkillsDescCriteria sdc : lst) {

            List<String> pointList = new ArrayList<>();
            int id = getDigramId(skill);
            int skillDescId = sdc.getId();
            if (sdc.getId() == id) {
                skillDescId = 0;
            }
            PanSkillDescCriteriaEdit pan = new PanSkillDescCriteriaEdit(skillDescId);
            pan.lblHeading.setText("<HTML>" + sdc.getType() + "</HTML>");
//            if (sdc.getView() == 1) {
//                pan.lblHeading.setForeground(Color.BLUE);
//            }
//            
//            pan.setId(sdc.getId());
            skillDescIdPanMap.put(sdc.getId(), pan);
            LinkedHashMap<String, Integer> pointsMap = new LinkedHashMap<>();

            i++;
            if (i <= rows) {
                panDesc1.add(pan);
            } else if (i <= (rows * 2)) {
                panDesc2.add(pan);
            }
            pan.setPointsMap(pointsMap);
        }
        if (!skill.equalsIgnoreCase(Skill.OP.getType()) && !skill.equalsIgnoreCase(Skill.TF.getType())) {

            for (Map.Entry<Integer, String> entry : rallyEvaluationSkillScore.getDetailsValues().entrySet()) {
                skillDescIdPanMap.get(entry.getKey()).setValue(entry.getValue());
            }
        }

    }

    public int getDigramId(String skill) {
        int id = 0;
        if (skill.equals(Skill.Service.getType())) {
            id = SkillsDescCriteria.ServiceDig.getId();
        } else if (skill.equals(Skill.Attack.getType())) {
            id = SkillsDescCriteria.AttackDig.getId();
        } else if (skill.equals(Skill.Block.getType())) {
            id = SkillsDescCriteria.BlockDig.getId();
        } else if (skill.equals(Skill.Set.getType())) {
            id = SkillsDescCriteria.SetDig.getId();
        } else if (skill.equals(Skill.Defence.getType())) {
            id = SkillsDescCriteria.DefenceDig.getId();
        } else if (skill.equals(Skill.Reception.getType())) {
            id = SkillsDescCriteria.ReceptionDig.getId();
        }
        return id;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSkill = new javax.swing.JLabel();
        txtChestNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panDesc1 = new javax.swing.JPanel();
        panDesc2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Skill");

        lblSkill.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblSkill.setText("jLabel2");

        txtChestNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChestNoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Chest No.");

        txtScore.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtScoreKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Rating");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtChestNo)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtScore)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtChestNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblSkill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        panDesc1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panDesc1Layout = new javax.swing.GroupLayout(panDesc1);
        panDesc1.setLayout(panDesc1Layout);
        panDesc1Layout.setHorizontalGroup(
            panDesc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
        panDesc1Layout.setVerticalGroup(
            panDesc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        panDesc2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panDesc2Layout = new javax.swing.GroupLayout(panDesc2);
        panDesc2.setLayout(panDesc2Layout);
        panDesc2Layout.setHorizontalGroup(
            panDesc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
        panDesc2Layout.setVerticalGroup(
            panDesc2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vollyball/images/button_save.png"))); // NOI18N
        jLabel4.setToolTipText("Save");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vollyball/images/button_cancel.png"))); // NOI18N
        jLabel5.setToolTipText("Cancel");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(panDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panDesc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panDesc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        int idm = rallyEvaluationSkillScore.getId();
        rallyEvaluationSkillScore = new RallyEvaluationSkillScore();
        rallyEvaluationSkillScore.setId(idm);

        code = getSkillCode(lblSkill.getText());

        code = code + "-" + txtChestNo.getText();

        rallyEvaluationSkillScore.setSkill(lblSkill.getText());
        rallyEvaluationSkillScore.setSkillId(Skill.getIdByName(lblSkill.getText()).getId());
        rallyEvaluationSkillScore.setScore(Integer.parseInt(txtScore.getText()));
        rallyEvaluationSkillScore.setChestNo(txtChestNo.getText());
        rallyEvaluationSkillScore.setPlayerId(Controller.panMatchSet.ChestMap.get(txtChestNo.getText()).getId());
        rallyEvaluationSkillScore.setCode("");

        for (Map.Entry<Integer, PanSkillDescCriteriaEdit> entry : skillDescIdPanMap.entrySet()) {
            int skillDescCriteriaId = entry.getKey();
            PanSkillDescCriteriaEdit panel = entry.getValue();

            rallyEvaluationSkillScore.getDetailsValues().put(skillDescCriteriaId, panel.value);

            if (!"".equals(panel.value) && !"".equals(panel.code)) {
                code = code + "-" + panel.code;
            }

        }
        code = code + "-" + getRating(Integer.parseInt(txtScore.getText()));
        p.txtInput.setText(code);
        rallyEvaluationSkillScore.setCode(code);
        p.update(rallyEvaluationSkillScore);
        p.dig.close();


    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtChestNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChestNoKeyTyped
        // TODO add your handling code here:
        checkNumber(evt, 0);
    }//GEN-LAST:event_txtChestNoKeyTyped

    private void txtScoreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtScoreKeyTyped
        // TODO add your handling code here:
        checkNumber(evt, 1);
    }//GEN-LAST:event_txtScoreKeyTyped

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
         p.dig.close();
    }//GEN-LAST:event_jLabel5MouseClicked

    public void checkNumber(java.awt.event.KeyEvent evt, int type) {
        ((JTextField) evt.getSource()).setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c))) {
            evt.consume();
        }
    }

    public String getSkillCode(String skill) {
        String code = "";
        switch (skill) {
            case "Service":
                code = "Q";
                break;
            case "Reception":
                code = "W";
                break;
            case "Attack":
                code = "E";
                break;
            case "Set":
                code = "R";
                break;
            case "Block":
                code = "T";
                break;
            case "Defence":
                code = "Y";
                break;
            default:
                break;

        }
        return code;
    }

    public String getRating(int rate) {
        String code = "";
        switch (rate) {
            case 1:
                code = "Z";
                break;
            case 2:
                code = "X";
                break;
            case 3:
                code = "C";
                break;
            case 4:
                code = "V";
                break;
            case 5:
                code = "B";
                break;

            default:
                code = "C";
                break;

        }
        return code;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSkill;
    private javax.swing.JPanel panDesc1;
    private javax.swing.JPanel panDesc2;
    private javax.swing.JTextField txtChestNo;
    private javax.swing.JTextField txtScore;
    // End of variables declaration//GEN-END:variables
}
