/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels;

import com.vollyball.bean.MatchSet;
import com.vollyball.bean.RallyEvaluation;
import com.vollyball.bean.SetTimeout;
import com.vollyball.controller.Controller;
import com.vollyball.dao.MatchDao;
import com.vollyball.dao.RallyDao;

/**
 *
 * @author nishant.vibhute
 */
public class PanEvaluationTimeout extends javax.swing.JPanel {

    MatchSet ms;
    RallyDao rallyDao = new RallyDao();
    MatchDao matchDao = new MatchDao();
    RallyEvaluation re;

    /**
     * Creates new form PanEvaluationTimeout
     */
    public PanEvaluationTimeout(int setNum, int matchEvaluationTeamId) {
        initComponents();
        this.ms = matchDao.getMatchSet(setNum, matchEvaluationTeamId);
        String evaluationName = Controller.panMatchEvaluationHome.getTeamsMap().get(ms.getEvaluationTeamId());
        String opponentName = Controller.panMatchEvaluationHome.getTeamsMap().get(ms.getOpponentTeamId());
        cmbTeam.addItem(evaluationName);
        cmbTeam.addItem(opponentName);

        int pos = matchDao.getTimeOutCount(ms.getId());
        pos++;
        cmPos.setSelectedItem("" + pos);

        txtRallyNo.setText("" + Controller.panMatchSet.currentRally);
        re = rallyDao.getRally(Integer.parseInt(txtRallyNo.getText()), ms.getId(), 0);
        txtScore.setText(re.getHomeScore() + " : " + re.getOpponentScore());

        for (SetTimeout s : ms.getSetTimeout()) {
            setTimeOut(s);
        }
    }

    public void setTimeOut(SetTimeout st) {
        String tm = st.getTeam();
        int scoreA = st.getScoreA();
        int scoreB = st.getScoreB();
        switch (st.getPosition()) {
            case 1:
                tm1.setText(tm);
                ScoreA1.setText("" + scoreA);
                ScoreB1.setText("" + scoreB);
                break;
            case 2:
                tm2.setText(tm);
                ScoreA2.setText("" + scoreA);
                ScoreB2.setText("" + scoreB);
                break;
            case 3:
                tm3.setText(tm);
                ScoreA3.setText("" + scoreA);
                ScoreB3.setText("" + scoreB);
                break;
            case 4:
                tm4.setText(tm);
                ScoreA4.setText("" + scoreA);
                ScoreB4.setText("" + scoreB);
                break;
            case 5:
                tm5.setText(tm);
                ScoreA5.setText("" + scoreA);
                ScoreB5.setText("" + scoreB);
                break;
            case 6:
                tm6.setText(tm);
                ScoreA6.setText("" + scoreA);
                ScoreB6.setText("" + scoreB);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRallyNo = new javax.swing.JTextField();
        txtScore = new javax.swing.JTextField();
        cmbTeam = new javax.swing.JComboBox();
        cmPos = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextField17 = new javax.swing.JTextField();
        tm1 = new javax.swing.JTextField();
        tm2 = new javax.swing.JTextField();
        tm3 = new javax.swing.JTextField();
        tm4 = new javax.swing.JTextField();
        tm5 = new javax.swing.JTextField();
        tm6 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        ScoreA1 = new javax.swing.JTextField();
        ScoreA2 = new javax.swing.JTextField();
        ScoreA3 = new javax.swing.JTextField();
        ScoreA4 = new javax.swing.JTextField();
        ScoreA5 = new javax.swing.JTextField();
        ScoreA6 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        ScoreB1 = new javax.swing.JTextField();
        ScoreB2 = new javax.swing.JTextField();
        ScoreB3 = new javax.swing.JTextField();
        ScoreB4 = new javax.swing.JTextField();
        ScoreB5 = new javax.swing.JTextField();
        ScoreB6 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        tm7 = new javax.swing.JTextField();
        tm8 = new javax.swing.JTextField();
        tm9 = new javax.swing.JTextField();
        tm10 = new javax.swing.JTextField();
        tm11 = new javax.swing.JTextField();
        tm12 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(57, 74, 108));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIMEOUT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("No : ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Team : ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Rally :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Score :");

        txtRallyNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRallyNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRallyNoFocusLost(evt);
            }
        });

        txtScore.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtScore.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtScore.setEnabled(false);

        cmbTeam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbTeam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));

        cmPos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmPos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vollyball/images/button_save.png"))); // NOI18N
        jLabel6.setToolTipText("Save");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRallyNo)
                            .addComponent(txtScore)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmPos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTeam, 0, 116, Short.MAX_VALUE))))
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRallyNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(255, 255, 255));
        jTextField17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("TM");
        jTextField17.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField17.setEnabled(false);

        tm1.setEditable(false);
        tm1.setBackground(new java.awt.Color(255, 255, 255));
        tm1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm1.setEnabled(false);

        tm2.setEditable(false);
        tm2.setBackground(new java.awt.Color(255, 255, 255));
        tm2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm2.setEnabled(false);

        tm3.setEditable(false);
        tm3.setBackground(new java.awt.Color(255, 255, 255));
        tm3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm3.setEnabled(false);

        tm4.setEditable(false);
        tm4.setBackground(new java.awt.Color(255, 255, 255));
        tm4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm4.setEnabled(false);

        tm5.setEditable(false);
        tm5.setBackground(new java.awt.Color(255, 255, 255));
        tm5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm5.setEnabled(false);

        tm6.setEditable(false);
        tm6.setBackground(new java.awt.Color(255, 255, 255));
        tm6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm6.setEnabled(false);
        tm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm6ActionPerformed(evt);
            }
        });

        jTextField51.setEditable(false);
        jTextField51.setBackground(new java.awt.Color(255, 255, 255));
        jTextField51.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField51.setText("A");
        jTextField51.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField51.setEnabled(false);

        ScoreA1.setEditable(false);
        ScoreA1.setBackground(new java.awt.Color(255, 255, 255));
        ScoreA1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreA1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreA1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreA1.setEnabled(false);

        ScoreA2.setEditable(false);
        ScoreA2.setBackground(new java.awt.Color(255, 255, 255));
        ScoreA2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreA2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreA2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreA2.setEnabled(false);

        ScoreA3.setEditable(false);
        ScoreA3.setBackground(new java.awt.Color(255, 255, 255));
        ScoreA3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreA3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreA3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreA3.setEnabled(false);

        ScoreA4.setEditable(false);
        ScoreA4.setBackground(new java.awt.Color(255, 255, 255));
        ScoreA4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreA4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreA4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreA4.setEnabled(false);

        ScoreA5.setEditable(false);
        ScoreA5.setBackground(new java.awt.Color(255, 255, 255));
        ScoreA5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreA5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreA5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreA5.setEnabled(false);

        ScoreA6.setEditable(false);
        ScoreA6.setBackground(new java.awt.Color(255, 255, 255));
        ScoreA6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreA6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreA6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreA6.setEnabled(false);

        jTextField58.setEditable(false);
        jTextField58.setBackground(new java.awt.Color(255, 255, 255));
        jTextField58.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField58.setText("B");
        jTextField58.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField58.setEnabled(false);

        ScoreB1.setEditable(false);
        ScoreB1.setBackground(new java.awt.Color(255, 255, 255));
        ScoreB1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreB1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreB1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreB1.setEnabled(false);

        ScoreB2.setEditable(false);
        ScoreB2.setBackground(new java.awt.Color(255, 255, 255));
        ScoreB2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreB2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreB2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreB2.setEnabled(false);

        ScoreB3.setEditable(false);
        ScoreB3.setBackground(new java.awt.Color(255, 255, 255));
        ScoreB3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreB3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreB3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreB3.setEnabled(false);

        ScoreB4.setEditable(false);
        ScoreB4.setBackground(new java.awt.Color(255, 255, 255));
        ScoreB4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreB4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreB4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreB4.setEnabled(false);

        ScoreB5.setEditable(false);
        ScoreB5.setBackground(new java.awt.Color(255, 255, 255));
        ScoreB5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreB5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreB5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreB5.setEnabled(false);

        ScoreB6.setEditable(false);
        ScoreB6.setBackground(new java.awt.Color(255, 255, 255));
        ScoreB6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ScoreB6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreB6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ScoreB6.setEnabled(false);

        jTextField18.setEditable(false);
        jTextField18.setBackground(new java.awt.Color(255, 255, 255));
        jTextField18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("No. ");
        jTextField18.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField18.setEnabled(false);

        tm7.setEditable(false);
        tm7.setBackground(new java.awt.Color(255, 255, 255));
        tm7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm7.setText("1");
        tm7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm7.setEnabled(false);

        tm8.setEditable(false);
        tm8.setBackground(new java.awt.Color(255, 255, 255));
        tm8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm8.setText("2");
        tm8.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm8.setEnabled(false);

        tm9.setEditable(false);
        tm9.setBackground(new java.awt.Color(255, 255, 255));
        tm9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm9.setText("3");
        tm9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm9.setEnabled(false);

        tm10.setEditable(false);
        tm10.setBackground(new java.awt.Color(255, 255, 255));
        tm10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm10.setText("4");
        tm10.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm10.setEnabled(false);

        tm11.setEditable(false);
        tm11.setBackground(new java.awt.Color(255, 255, 255));
        tm11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm11.setText("5");
        tm11.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm11.setEnabled(false);

        tm12.setEditable(false);
        tm12.setBackground(new java.awt.Color(255, 255, 255));
        tm12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tm12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tm12.setText("6");
        tm12.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tm12.setEnabled(false);
        tm12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(tm6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ScoreB1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ScoreB2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ScoreB3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ScoreB4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ScoreB5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ScoreA1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ScoreA2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ScoreA3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ScoreA4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(ScoreA5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScoreA6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScoreB6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tm6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreA1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreA2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreA3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreA4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreA5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreA6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreB1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreB2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreB3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreB4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreB5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScoreB6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tm6ActionPerformed

    private void txtRallyNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRallyNoFocusLost
        // TODO add your handling code here:
        re = rallyDao.getRally(Integer.parseInt(txtRallyNo.getText()), ms.getId(), 0);
        txtScore.setText(re.getHomeScore() + " : " + re.getOpponentScore());
    }//GEN-LAST:event_txtRallyNoFocusLost

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        String score[] = txtScore.getText().split(":");

        SetTimeout st = new SetTimeout();
        st.setPosition(Integer.parseInt("" + cmPos.getSelectedItem()));
        st.setTeam("" + cmbTeam.getSelectedItem());
        st.setScoreA(Integer.parseInt(score[0].trim()));
        st.setScoreB(Integer.parseInt(score[1].trim()));
        st.setMatchEvalId(ms.getId());
        int id = matchDao.insertTimeout(st, re.getId());

        if (id == 0) {

        } else {
            Controller.panMatchSet.dialogEvaluationTimeout.close();
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void tm12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tm12ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ScoreA1;
    private javax.swing.JTextField ScoreA2;
    private javax.swing.JTextField ScoreA3;
    private javax.swing.JTextField ScoreA4;
    private javax.swing.JTextField ScoreA5;
    private javax.swing.JTextField ScoreA6;
    private javax.swing.JTextField ScoreB1;
    private javax.swing.JTextField ScoreB2;
    private javax.swing.JTextField ScoreB3;
    private javax.swing.JTextField ScoreB4;
    private javax.swing.JTextField ScoreB5;
    private javax.swing.JTextField ScoreB6;
    private javax.swing.JComboBox cmPos;
    private javax.swing.JComboBox cmbTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField tm1;
    private javax.swing.JTextField tm10;
    private javax.swing.JTextField tm11;
    private javax.swing.JTextField tm12;
    private javax.swing.JTextField tm2;
    private javax.swing.JTextField tm3;
    private javax.swing.JTextField tm4;
    private javax.swing.JTextField tm5;
    private javax.swing.JTextField tm6;
    private javax.swing.JTextField tm7;
    private javax.swing.JTextField tm8;
    private javax.swing.JTextField tm9;
    private javax.swing.JTextField txtRallyNo;
    private javax.swing.JTextField txtScore;
    // End of variables declaration//GEN-END:variables
}
