/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

/**
 *
 * @author Supriya
 */
public class PanMatchConsolidatedReportHome extends javax.swing.JPanel {

    PanMatchReportConsolidated panC;
    PanZoneSkillwiseMain panZ;
    PanZoneRotationMain panR;
    int cb, matchId;

    /**
     * Creates new form PanMatchConsolidatedReportHome
     */
    public PanMatchConsolidatedReportHome(int cb, int matchId) {
        initComponents();
        this.cb = cb;
        this.matchId = matchId;
        panC = new PanMatchReportConsolidated(cb, matchId);
        panReport.add(panC, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panPrint1 = new javax.swing.JPanel();
        lblPrint1 = new javax.swing.JLabel();
        scrPan = new javax.swing.JScrollPane();
        panReport = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblmatchReport = new javax.swing.JLabel();
        lblRotationReport = new javax.swing.JLabel();
        lblSkilReport = new javax.swing.JLabel();

        panPrint1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPrint1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPrint1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrint1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vollyball/images/printer.png"))); // NOI18N
        lblPrint1.setToolTipText("Print This Page");
        lblPrint1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrint1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panPrint1Layout = new javax.swing.GroupLayout(panPrint1);
        panPrint1.setLayout(panPrint1Layout);
        panPrint1Layout.setHorizontalGroup(
            panPrint1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrint1Layout.createSequentialGroup()
                .addComponent(lblPrint1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );
        panPrint1Layout.setVerticalGroup(
            panPrint1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrint1Layout.createSequentialGroup()
                .addComponent(lblPrint1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(621, 621, 621)
                .addComponent(panPrint1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrint1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panReport.setLayout(new java.awt.BorderLayout());
        scrPan.setViewportView(panReport);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblmatchReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmatchReport.setText("Match");
        lblmatchReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblmatchReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmatchReportMouseClicked(evt);
            }
        });

        lblRotationReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRotationReport.setText("Rotation");
        lblRotationReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblRotationReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRotationReportMouseClicked(evt);
            }
        });

        lblSkilReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSkilReport.setText("Skill");
        lblSkilReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSkilReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSkilReportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRotationReport, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSkilReport, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(lblmatchReport, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 687, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRotationReport, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(lblSkilReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblmatchReport, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrPan)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrPan, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblPrint1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrint1MouseClicked
        // TODO add your handling code here:
        panPrint1.setVisible(false);
        printComponenet(panC);
        panPrint1.setVisible(true);

    }//GEN-LAST:event_lblPrint1MouseClicked

    private void lblmatchReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmatchReportMouseClicked
        // TODO add your handling code here:
        panReport.removeAll();
        panC = new PanMatchReportConsolidated(cb, matchId);
        panReport.add(panC, BorderLayout.CENTER);
        validate();
        repaint();

    }//GEN-LAST:event_lblmatchReportMouseClicked

    private void lblRotationReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRotationReportMouseClicked
        // TODO add your handling code here:
        panReport.removeAll();
        panR = new PanZoneRotationMain(cb, matchId);
        panReport.add(panR, BorderLayout.CENTER);
        validate();
        repaint();
    }//GEN-LAST:event_lblRotationReportMouseClicked

    private void lblSkilReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSkilReportMouseClicked
        // TODO add your handling code here:
        panReport.removeAll();
        panZ = new PanZoneSkillwiseMain(cb, matchId);
        panReport.add(panZ, BorderLayout.CENTER);
        validate();
        repaint();
    }//GEN-LAST:event_lblSkilReportMouseClicked

    public void printComponenet(final Component comp) {

        PageFormat documentPageFormat = new PageFormat();
//        documentPageFormat.setOrientation(PageFormat.LANDSCAPE);

        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName("Score Report_-_");

        pj.setPrintable(new Printable() {
            public int print(Graphics g, PageFormat format, int page_index)
                    throws PrinterException {
                if (page_index > 0) {
                    return Printable.NO_SUCH_PAGE;
                }

//                format.setOrientation(PageFormat.LANDSCAPE);
                // get the bounds of the component
                Dimension dim = comp.getSize();
                double cHeight = dim.getHeight();
                double cWidth = dim.getWidth();

                // get the bounds of the printable area
                double pHeight = format.getImageableHeight();
                double pWidth = format.getImageableWidth();

                double pXStart = format.getImageableX();
                double pYStart = format.getImageableY();

                double xRatio = pWidth / cWidth;
                double yRatio = pHeight / cHeight;

                Graphics2D g2 = (Graphics2D) g;
                g2.translate(pXStart, pYStart);
                g2.scale(xRatio, yRatio);
                comp.printAll(g2);

                return Printable.PAGE_EXISTS;
            }
        }, documentPageFormat);
        if (pj.printDialog() == false) {
            return;
        }

        try {
            pj.print();
        } catch (PrinterException ex) {
            // handle exception
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPrint1;
    private javax.swing.JLabel lblRotationReport;
    private javax.swing.JLabel lblSkilReport;
    private javax.swing.JLabel lblmatchReport;
    private javax.swing.JPanel panPrint1;
    private javax.swing.JPanel panReport;
    private javax.swing.JScrollPane scrPan;
    // End of variables declaration//GEN-END:variables
}
