/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels;

import com.vollyball.enums.SkillDescCriteriaPoint;
import com.vollyball.enums.SkillsDescCriteria;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author nishant.vibhute
 */
public class PanPostSkillDetailsCriteriaRow extends javax.swing.JPanel {

    int skillDescId;
    String value;

    /**
     * Creates new form PanPostSkillDetailsCriteriaRow
     */
    public PanPostSkillDetailsCriteriaRow(String typeValue) {
        initComponents();
        ((JLabel) cmbvalue.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);

        lbltype.setText(typeValue);
        int skillDescId = SkillsDescCriteria.getTypeByName(lbltype.getText()).getId();
        List<SkillDescCriteriaPoint> list = SkillDescCriteriaPoint.getTypeBySkillDescId(skillDescId);
        for (SkillDescCriteriaPoint cb : list) {
            cmbvalue.addItem(cb.getAbbreviation());
        }

    }

    public void setValue(String value) {
        cmbvalue.setSelectedItem(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cmbvalue = new javax.swing.JComboBox();
        lbltype = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        cmbvalue.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbvalue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        cmbvalue.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbvalueItemStateChanged(evt);
            }
        });

        lbltype.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbltype.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbltype, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(cmbvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmbvalue)
            .addComponent(lbltype, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbvalueItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbvalueItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            skillDescId = SkillsDescCriteria.getTypeByName(lbltype.getText()).getId();
            value = evt.getItem().toString();
            if (value.equals("Select")) {
                skillDescId = 0;
            }
        }

    }//GEN-LAST:event_cmbvalueItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbvalue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lbltype;
    // End of variables declaration//GEN-END:variables
}
