/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels;

import com.vollyball.bean.Player;
import com.vollyball.controller.Controller;
import com.vollyball.dialog.CreateRallyRotationDialog;
import java.awt.Color;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author nishant.vibhute
 */
public class PanRallyRotation extends javax.swing.JPanel {

    Color cG = Color.ORANGE;
    LinkedHashMap<Integer, Player> rallyPositionMap;
    List<JTextField> posTextFileds = new ArrayList<>();
    CreateRallyRotationDialog obj;

    /**
     * Creates new form PanRallyRotation
     */
    public PanRallyRotation(CreateRallyRotationDialog obj) {
        initComponents();
        this.rallyPositionMap = Controller.panMatchSet.rallyPositionMap;
        this.obj = obj;
        pos1.setText(rallyPositionMap.get(1).getChestNo());
        pos2.setText(rallyPositionMap.get(2).getChestNo());
        pos3.setText(rallyPositionMap.get(3).getChestNo());
        pos4.setText(rallyPositionMap.get(4).getChestNo());
        pos5.setText(rallyPositionMap.get(5).getChestNo());
        pos6.setText(rallyPositionMap.get(6).getChestNo());

        posTextFileds.add(pos1);
        posTextFileds.add(pos2);
        posTextFileds.add(pos3);
        posTextFileds.add(pos4);
        posTextFileds.add(pos5);
        posTextFileds.add(pos6);
    }

    public void setPlayer(java.awt.event.KeyEvent evt, int pos) {
        JTextField jf = (JTextField) evt.getSource();
        String item = jf.getText();
        if (item.length() > 1) {
            if (Controller.panMatchSet.ChestMap.containsKey(item)) {
                for (Map.Entry<Integer, Player> entry : rallyPositionMap.entrySet()) {
                    if (entry.getKey() != 7) {
                        if (!rallyPositionMap.get(pos).getChestNo().equals(jf.getText())) {
                            Player pl = entry.getValue();
                            if (pl.getChestNo().equals(jf.getText())) {
                                jf.setText("");
                            }
                        }
                    }
                }
            } else {
                jf.setText("");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pos4 = new javax.swing.JTextField();
        pos3 = new javax.swing.JTextField();
        pos2 = new javax.swing.JTextField();
        pos5 = new javax.swing.JTextField();
        pos6 = new javax.swing.JTextField();
        pos1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblOk = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(54, 78, 108)));

        jPanel2.setBackground(new java.awt.Color(54, 78, 108));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ROTATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pos4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pos4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pos4.setCaretColor(new java.awt.Color(255, 255, 255));
        pos4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pos4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pos4FocusLost(evt);
            }
        });
        pos4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pos4KeyReleased(evt);
            }
        });

        pos3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pos3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pos3.setCaretColor(new java.awt.Color(255, 255, 255));
        pos3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pos3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pos3FocusLost(evt);
            }
        });
        pos3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pos3KeyReleased(evt);
            }
        });

        pos2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pos2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pos2.setCaretColor(new java.awt.Color(255, 255, 255));
        pos2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pos2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pos2FocusLost(evt);
            }
        });
        pos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pos2KeyReleased(evt);
            }
        });

        pos5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pos5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pos5.setCaretColor(new java.awt.Color(255, 255, 255));
        pos5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pos5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pos5FocusLost(evt);
            }
        });
        pos5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pos5KeyReleased(evt);
            }
        });

        pos6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pos6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pos6.setCaretColor(new java.awt.Color(255, 255, 255));
        pos6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pos6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pos6FocusLost(evt);
            }
        });
        pos6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pos6KeyReleased(evt);
            }
        });

        pos1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pos1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pos1.setCaretColor(new java.awt.Color(255, 255, 255));
        pos1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pos1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pos1FocusLost(evt);
            }
        });
        pos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pos1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pos4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pos3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pos2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pos5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pos6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(57, 74, 108));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblOk.setBackground(new java.awt.Color(255, 255, 255));
        lblOk.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOk.setForeground(new java.awt.Color(255, 255, 255));
        lblOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOk.setText("OK");
        lblOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOk, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pos2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos2FocusLost

        pos2.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_pos2FocusLost

    private void pos1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos1FocusGained

        pos1.setBorder(BorderFactory.createLineBorder(cG));
    }//GEN-LAST:event_pos1FocusGained

    private void pos1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos1FocusLost

        pos1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_pos1FocusLost

    private void pos2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos2FocusGained

        pos2.setBorder(BorderFactory.createLineBorder(cG));
    }//GEN-LAST:event_pos2FocusGained

    private void pos6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos6FocusLost

        pos6.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_pos6FocusLost

    private void pos6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos6FocusGained

        pos6.setBorder(BorderFactory.createLineBorder(cG));
    }//GEN-LAST:event_pos6FocusGained

    private void pos5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos5FocusLost

        pos5.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_pos5FocusLost

    private void pos5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos5FocusGained

        pos5.setBorder(BorderFactory.createLineBorder(cG));
    }//GEN-LAST:event_pos5FocusGained

    private void pos3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos3FocusLost

        pos3.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_pos3FocusLost

    private void pos3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos3FocusGained

        pos3.setBorder(BorderFactory.createLineBorder(cG));
    }//GEN-LAST:event_pos3FocusGained

    private void pos4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos4FocusLost

        pos4.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }//GEN-LAST:event_pos4FocusLost

    private void pos4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pos4FocusGained

        pos4.setBorder(BorderFactory.createLineBorder(cG));
    }//GEN-LAST:event_pos4FocusGained

    private void pos1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pos1KeyReleased

        setPlayer(evt, 1);
    }//GEN-LAST:event_pos1KeyReleased

    private void pos2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pos2KeyReleased

        setPlayer(evt, 2);
    }//GEN-LAST:event_pos2KeyReleased

    private void pos3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pos3KeyReleased

        setPlayer(evt, 3);
    }//GEN-LAST:event_pos3KeyReleased

    private void pos4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pos4KeyReleased

        setPlayer(evt, 4);
    }//GEN-LAST:event_pos4KeyReleased

    private void pos5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pos5KeyReleased

        setPlayer(evt, 5);
    }//GEN-LAST:event_pos5KeyReleased

    private void pos6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pos6KeyReleased

        setPlayer(evt, 6);
    }//GEN-LAST:event_pos6KeyReleased

    private void lblOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOkMouseClicked
        // TODO add your handling code here:
        boolean isValidate = true;
        boolean isExist = true;
        for (JTextField jf : posTextFileds) {
            if (jf.getText().equals("")) {
                isValidate = false;
                jf.setBorder(new LineBorder(Color.RED));

            } else {
                if (Controller.panMatchSet.ChestMap.get(jf.getText()) == null) {
                    isExist = false;
                    jf.setBorder(new LineBorder(Color.RED));

                }
            }
        }
        if (isValidate && isExist) {
            int i = 1;
            for (JTextField jf : posTextFileds) {
                Controller.panMatchSet.rallyPositionMap.put(i, Controller.panMatchSet.ChestMap.get(jf.getText()));
                i++;
            }
            obj.close();
        } else if (!isExist) {
            JOptionPane.showMessageDialog(this, "Player Chest number not Exist");
        } else {
            JOptionPane.showMessageDialog(this, "Players cannot be empty");
        }

    }//GEN-LAST:event_lblOkMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblOk;
    private javax.swing.JTextField pos1;
    private javax.swing.JTextField pos2;
    private javax.swing.JTextField pos3;
    private javax.swing.JTextField pos4;
    private javax.swing.JTextField pos5;
    private javax.swing.JTextField pos6;
    // End of variables declaration//GEN-END:variables
}
