/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels;

/**
 *
 * @author nishant.vibhute
 */
public class PanSettingsRow extends javax.swing.JPanel {

    /**
     * Creates new form PanSttingsRow
     */
    public PanSettingsRow(int srNo, String longForm, String abbr, String Code) {

        initComponents();
        lblSRNo.setText("" + srNo);
        lblLongForm.setText(longForm);
        lblAbbr.setText(abbr);
        txtCode.setText(Code);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSRNo = new javax.swing.JLabel();
        lblLongForm = new javax.swing.JLabel();
        lblAbbr = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblSRNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSRNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSRNo.setText("1");

        lblLongForm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblAbbr.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAbbr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtCode.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblSRNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLongForm, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAbbr, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtCode, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSRNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblLongForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAbbr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAbbr;
    private javax.swing.JLabel lblLongForm;
    private javax.swing.JLabel lblSRNo;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
