/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vollyball.panels;

import java.awt.Dimension;
import javax.swing.table.JTableHeader;

/**
 *
 * @author nishant.vibhute
 */
public class PanTeams extends javax.swing.JPanel {

    /**
     * Creates new form PanTeams
     */
    public PanTeams() {
        initComponents();
        JTableHeader th = tbTeamList.getTableHeader();
        th.setPreferredSize(new Dimension(50, 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTeamList = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 51, 255));
        setLayout(new java.awt.BorderLayout());

        tbTeamList.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbTeamList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No", "Name"
            }
        ));
        tbTeamList.setRowHeight(25);
        tbTeamList.setRowMargin(2);
        jScrollPane1.setViewportView(tbTeamList);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbTeamList;
    // End of variables declaration//GEN-END:variables
}
